### ISSUE TITLE
Suprising behavior when argument is not already a string

### ISSUE THREAD

**Issue by pkoch** [gadget-inc/minitest-snapshots#5]
```
$ cat test/lib/example_test.rb
require "test_helper"

describe "problem" do
  it "exemplifies" do
    assert_matches_snapshot a: 1
  end
end

$ rails t test/lib/example_test.rb 
Run options: --seed 40581

# Running:

.

Finished in 0.001819s, 549.8112 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 0 errors, 0 skips

$ rails t test/lib/example_test.rb 
Run options: --seed 3981

# Running:

F

Failure:
problem#test_0001_exemplifies [/home/pkoch/example/test/lib/example_test.rb:5]:
The string does not match the snapshot (located at /home/pkoch/example/test/snapshots/problem/test_0001_exemplifies__1.snap.txt).
Expected: "{:a=>1}"
  Actual: {:a=>1}


rails test test/lib/example_test.rb:4



Finished in 0.002081s, 480.5744 runs/s, 480.5744 assertions/s.
1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
```

I'm sure everyone would agree tests should be idempotent. :P The quick fix for this would be to add a `string = string.to_s` at the start of `assert_matches_snapshot`.

Would you be open to a PR for that?

**Comment by airhorns** [comment]
Yeah, I think it'd be more programmer friendly that way for sure. I think there's a couple ways it could burn you: if you pass in an object that isn't a string that doesn't respond to `#to_s` and if the `#to_s` isn't deterministic / stable. With Hashes specifically I don't think it is as the iteration order depends on insertion order I believe. I've used a stable JSON serializer before to be more robust to that kind of thing which might be a better option for non-string snapshots anyways.

**Comment by pkoch** [comment]
I disagree with you, but I think there's merit in your perspective.

Indeed, some objects have string representations that you can't really rely upon for snapshotting. However, you're always going to write a string to a file, and you're always going to compare the argument with the string you read from the file in the next test run. That's an inescapable fact, which puts me at ease to suggest forcing the use of `to_s` (and calling that on a string returns itself). I think that people that don't take enough care to pass a reliable stringable won't be helped by the current behavior, but the people who do are now forced to have useless `to_s`s sprinkled in their tests.

The obvious alternative here would be to raise if the argument supplied is not already a string, instead of implicitly converting it when we call `file.write`. There's some value in forcing the caller to chose what bytes represent the object they want to see not changed. I don't think that value is greater than the neatness afforded by not having to `to_s` everywhere, since that's going to be the overwhelming majority of cases [1].

There's also the alternative of having `assert_matches_snapshot` call a serializer depending on the passed object, and a deserializer when we read the file. This feels like major overkill, greatly expands the scope of the gem, and we don't get anything a caller wouldn't be better equipped than us to solve, anyway.

I'm keeping my stance of favoring calling `to_s` inside `assert_matches_snapshot`. Most people will benefit from that, those that forget to take care to pass in something repeatable will be presented with a clear enough symptom, and it won't ever get in anybody's way.

What say you, package maintainer, ruler of APIs? :P

[1]: I'm guessing. I tried to look around for reverse dependencies, and there's none. So there's no data to help us decide here. :/

**Comment by chocolateboy** [comment]
[Marshal](https://ruby-doc.org/core-2.7.1/Marshal.html) seems like the natural tool for this, although (like JSON) it doesn't provide a built-in way to [canonicalize](https://perldoc.perl.org/Storable.html#CANONICAL-REPRESENTATION) Hash keys or Set elements.

**Comment by airhorns** [comment]
Marshal would work ok but in my experience mucking around with snapshots in the `jest` world where I learned about them I often was actually looking at the contents, so I'd put human readability of the snapshot up there as an important piece too. Marshal doesn't do super great with human readability because it uses non-ascii bytes pretty frequently. How would y'all feel about YAML?

**Comment by chocolateboy** [comment]
Good point. The only way to be sure the tests are working correctly is to check the human-readable representation of the snapshot, which might as well be the actual snapshot (yes, YAML would be great).

**Comment by pkoch** [comment]
🚀🎉🥰

Thank you very much, folks!
